addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.5.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                      % "2.3.6")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"                % "1.5.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.4.2")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-github-actions"  % "0.4.18")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-native"          % "sbt-scala-native"              % "0.4.10")
