addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.5.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                      % "2.3.7")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"                % "1.5.12")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.4.2")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-github-actions"  % "0.5.2")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-native"          % "sbt-scala-native"              % "0.4.12")
