addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"           % "2.3.5")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"     % "1.5.10")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.4.1")
addSbtPlugin("com.codecommit"            % "sbt-github-actions" % "0.14.2")
